name: Docker
on:
  pull_request:
    paths:
      - add_me_to_your_PATH/Dockerfile.template
      - add_me_to_your_PATH/sysimage.jl
      - add_me_to_your_PATH/startup.jl
      - .github/workflows/docker.yaml

# Each PR and each commit on `main` use distinct concurrency groups. Note canceling workflows in
# progress may result in having to rebuild layers as the Docker layer caching is only uploaded
# once the image has been fully built. That said, new commits may invalidate these layers anyway.
concurrency:
  group: image-build-${{ github.ref_name }}-${{ github.ref == 'refs/heads/main' && github.run_number }}
  cancel-in-progress: true

jobs:
  build:
    name: Image Build
    runs-on: ubuntu-latest
    env:
      # Reference the HEAD commit which triggerred this workflow. By default PRs use a merge commit
      SHA: ${{ github.event.pull_request.head.sha || github.sha }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.SHA }}  # Always checkout HEAD commit
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Generate project
        run: |
          mkdir julia_pod dev src
          echo "Example" >julia_pod/sysimage.packages
          cp add_me_to_your_PATH/sysimage.jl add_me_to_your_PATH/startup.jl julia_pod/
          JULIA_PKG_PRECOMPILE_AUTO=0 julia --project=. -e '
              using Pkg;
              Pkg.generate("CITest");
              Pkg.activate("CITest");
              Pkg.add(["Example", "Mocking"])'
          mv CITest/* .
      - name: Build
        uses: docker/build-push-action@v4
        with:
          # Use Path context to ensure that our generated `julia_pod` directory is included in the image.
          # https://github.com/docker/build-push-action#git-context
          context: .
          push: false
          file: add_me_to_your_PATH/Dockerfile.template
          build-args: |
            JULIA_VERSION=1
            CUDA_VERSION=12.1.1
          cache-from: type=gha
          cache-to: type=gha,mode=max
